$(document).ready(function(){
  $('#top_owl').owlCarousel({
    autoplay:false,
    autoplayTimeout:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
}),
 $('#owl_bot').owlCarousel({
    autoplay:true,
    autoplayTimeout:3000,
    loop:true,
    margin:10,
    nav:true,
    navText: ["",""],
    dots: false,
    responsive:{
        0:{
            items:1
        },
        450:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})
});
